# roles/jenkins/tasks/main.yml

- name: Create namespace if not exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ helm_namespace }}"
    state: present

- name: Add Jenkins Helm repo
  kubernetes.core.helm_repository:
    name: jenkins
    repo_url: https://charts.jenkins.io

- name: Install Jenkins with Helm
  kubernetes.core.helm:
    name: "{{ jenkins_release_name }}"
    chart_ref: jenkins/jenkins
    release_namespace: "{{ helm_namespace }}"
    create_namespace: false
    values_files:
      - "{{ jenkins_values_template }}"
    version: "{{ jenkins_chart_version }}"
