# roles/jenkins/tasks/main.yml

- name: Create namespace if not exists
  shell: |
    kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}
  delegate_to: localhost

- name: Add Jenkins Helm repo
  shell: |
    helm repo add jenkins https://charts.jenkins.io || true
    helm repo update
  delegate_to: localhost

- name: Install Jenkins with Helm
  shell: |
    helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
      --namespace {{ helm_namespace }} \
      --create-namespace=false \
      --values {{ jenkins_values_template }} \
      --version {{ jenkins_chart_version }}
  args:
    chdir: "{{ playbook_dir }}/roles/jenkins/templates"  # donde está values.yaml.j2 generado
  delegate_to: localhost