# playbooks\create_jenkins_ingress.yml
---
- name: Crear Ingress para Jenkins
  hosts: controller
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  environment:
    KUBECONFIG: "/home/victory/.kube/config"

  tasks:
    - name: Aplicar Ingress de Jenkins
      template:
        src: ../templates/jenkins/jenkins-ingress.yaml.j2
        dest: /tmp/jenkins-ingress.yaml

    - name: Aplicar recurso Ingress en Kubernetes
      shell: kubectl apply -f /tmp/jenkins-ingress.yaml