# playbooks/install_jenkins.yml

- name: Install Jenkins with Helm
  hosts: masters
  gather_facts: false
  serial: 1
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Renderizar values.yaml.j2 en /tmp/values.yaml en el controlador
      ansible.builtin.template:
        src: ../roles/jenkins/templates/values.yaml.j2
        dest: /tmp/values.yaml
      delegate_to: localhost

    - name: Copiar values.yaml al master usando scp automático
      ansible.builtin.shell: |
        scp -i /root/.ssh/cluster_k3s/shared/id_rsa_shared_cluster -o StrictHostKeyChecking=no /tmp/values.yaml core@{{ inventory_hostname }}:/home/core/values.yaml
      delegate_to: localhost

    - name: Verificar conexión al API Server de Kubernetes
      ansible.builtin.shell: |
        kubectl get nodes
      register: kubectl_check
      ignore_errors: yes
      delegate_to: localhost

    - name: Fallar si no hay conexión al cluster
      ansible.builtin.fail:
        msg: "No hay conexión al cluster Kubernetes. Revisa tu kubeconfig."
      when: kubectl_check.rc != 0
      delegate_to: localhost

    - name: Crear namespace si no existe
      ansible.builtin.shell: |
        kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}
      delegate_to: localhost

    - name: Añadir repositorio de Helm para Jenkins
      ansible.builtin.shell: |
        helm repo add jenkins https://charts.jenkins.io || true
        helm repo update
      delegate_to: localhost

    - name: Instalar Jenkins usando Helm
      ansible.builtin.shell: |
        helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
          --namespace {{ helm_namespace }} \
          --create-namespace=false \
          --values /home/core/values.yaml \
          --version {{ jenkins_chart_version }}
      delegate_to: localhost

    - meta: end_play