# playbooks\install_jenkins.yml
- name: Install Jenkins with Helm
  hosts: masters
  gather_facts: false
  serial: 1
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Copiar values.yaml.j2 a /tmp/values.yaml en el controlador
      ansible.builtin.copy:
        src: ../roles/jenkins/templates/values.yaml.j2
        dest: /tmp/values.yaml
      delegate_to: localhost

    - name: Copiar values.yaml al master usando scp automático
      ansible.builtin.shell: |
        scp -i /root/.ssh/cluster_k3s/shared/id_rsa_shared_cluster -o StrictHostKeyChecking=no /tmp/values.yaml core@{{ inventory_hostname }}:/home/core/values.yaml
      delegate_to: localhost

    - name: Crear namespace si no existe
      raw: |
        kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}

    - name: Añadir repositorio de Helm para Jenkins
      raw: |
        helm repo add jenkins https://charts.jenkins.io || true
        helm repo update

    - name: Instalar Jenkins usando Helm
      raw: |
        helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
          --namespace {{ helm_namespace }} \
          --create-namespace=false \
          --values /home/core/values.yaml \
          --version {{ jenkins_chart_version }}

    - meta: end_play # Fin del playbook
