# playbooks\install_jenkins.yml
- name: Install Jenkins with Helm
  hosts: masters
  become: yes
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml   # <<-- 🔥 Cargamos manualmente las variables
  roles:
    - jenkins