# playbooks\install_jenkins.yml
- name: Install Jenkins with Helm
  hosts: masters
  gather_facts: false
  serial: 1              # <--- Solo un nodo a la vez
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Copiar values.yaml.j2 a /home/core/values.yaml en el controlador
      ansible.builtin.copy:
        src: ../roles/jenkins/templates/values.yaml.j2
        dest: /tmp/values.yaml
      delegate_to: localhost

    - name: Copiar values.yaml en el master
      ansible.builtin.copy:
        src: /tmp/values.yaml    # <--- ⚡ muy importante cambiarlo
        dest: /home/core/values.yaml
        owner: core
        group: core
        mode: '0644'
        remote_src: no           # <--- ⚡ MUY IMPORTANTE para que se copie desde tu máquina (controlador) al nodo



    - name: Crear namespace si no existe
      raw: |
        kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}

    - name: Añadir repositorio de Helm para Jenkins
      raw: |
        helm repo add jenkins https://charts.jenkins.io || true
        helm repo update

    - name: Instalar Jenkins usando Helm
      raw: |
        helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
          --namespace {{ helm_namespace }} \
          --create-namespace=false \
          --values /home/core/values.yaml \
          --version {{ jenkins_chart_version }}

    - meta: end_play    # 🔥 Después de ejecutar en el primer nodo, terminamos