# playbooks\install_jenkins.yml
---
# Playbook para instalar o actualizar Jenkins en Kubernetes utilizando Helm
- name: Instalar o actualizar Jenkins utilizando Helm
  hosts: controller
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    KUBECONFIG: "/home/victory/.kube/config"

  tasks:
    # Confirmar carga de las variables
    - name: Confirmar carga de variables
      debug:
        msg: "✅ Variables cargadas correctamente."

    # Renderizar el archivo values.yaml en el controller
    - name: Renderizar values.yaml.j2 en el controller
      template:
        src: ../templates/jenkins/values.yaml.j2
        dest: /tmp/values.yaml

    # Crear namespace si no existe
    - name: Crear namespace si no existe
      shell: |
        kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}

    # Crear secreto de autenticación básica si no existe
    - name: Crear secreto de autenticación básica si no existe
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: jenkins-auth-secret
            namespace: "{{ helm_namespace }}"
          type: Opaque
          data:
            auth-basic: "{{ lookup('file', 'files/htpasswd.txt') | b64encode }}"

    # Añadir repositorio de Helm para Jenkins
    - name: Añadir repositorio de Helm para Jenkins
      shell: |
        helm repo add jenkins https://charts.jenkins.io || true
        helm repo update

    # Instalar o actualizar Jenkins utilizando Helm a la versión 2.504.1
    - name: Instalar o actualizar Jenkins utilizando Helm
      shell: |
        helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
          --namespace {{ helm_namespace }} \
          --create-namespace=false \
          --values /tmp/values.yaml \
          --version 2.504.1

    # Esperar la instalación de Jenkins
    - name: Esperar a que Jenkins esté completamente desplegado
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ helm_namespace }}"
        name: "{{ jenkins_release_name }}-0"
      register: jenkins_pod_info
      until: jenkins_pod_info.resources[0].status.phase == "Running"
      retries: 10
      delay: 15
      timeout: 180
