# playbooks/install_jenkins.yml

- name: Install Jenkins with Helm
  hosts: masters
  gather_facts: false
  serial: 1
  vars_files:
    - ../group_vars/all.yml
  vars:
    ansible_shell_executable: /bin/bash    # 🔥 Usa bash directamente
    ansible_python_interpreter: /bin/false  # 🔥 NO uses Python (porque no hay)


  tasks:
    - name: Copiar values.yaml.j2 a /tmp/values.yaml en el controlador
      ansible.builtin.copy:
        src: roles/jenkins/templates/values.yaml.j2
        dest: /tmp/values.yaml
      delegate_to: localhost

    - name: Copiar values.yaml al master usando scp automático
      ansible.builtin.shell: |
        scp -i /root/.ssh/cluster_k3s/shared/id_rsa_shared_cluster -o StrictHostKeyChecking=no /tmp/values.yaml core@{{ inventory_hostname }}:/home/core/values.yaml
      delegate_to: localhost

    - name: Crear namespace si no existe (directo en el master)
      ansible.builtin.shell: |
        kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}
      args:
        executable: /bin/bash

    - name: Añadir repositorio de Helm para Jenkins (directo en el master)
      ansible.builtin.shell: |
        helm repo add jenkins https://charts.jenkins.io || true
        helm repo update
      args:
        executable: /bin/bash

    - name: Instalar Jenkins usando Helm (directo en el master)
      ansible.builtin.shell: |
        helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
          --namespace {{ helm_namespace }} \
          --create-namespace=false \
          --values /home/core/values.yaml \
          --version {{ jenkins_chart_version }}
      args:
        executable: /bin/bash

    - meta: end_play