# playbooks\install_jenkins.yml
---  
# 🧩 Despliegue de Jenkins en Kubernetes desde el controller

- name: Instalar Jenkins en Kubernetes desde el controller
  hosts: controller
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml
  environment:
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    KUBECONFIG: "/home/victory/.kube/config"

  tasks:
    - name: Confirmar carga de variables
      debug:
        msg: "✅ Variables cargadas correctamente."

    - name: Renderizar values.yaml.j2 en el controller
      template:
        src: ../templates/jenkins/values.yaml.j2
        dest: /tmp/values.yaml

    - name: Crear namespace si no existe
      shell: |
        kubectl get namespace {{ helm_namespace }} || kubectl create namespace {{ helm_namespace }}

    - name: Crear secreto de autenticación básica si no existe
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: jenkins-auth-secret
            namespace: "{{ helm_namespace }}"
          type: Opaque
          data:
            auth-basic: "{{ lookup('file', 'playbooks/files/htpasswd.txt') | b64encode }}"

    - name: Añadir repositorio de Helm para Jenkins
      shell: |
        helm repo add jenkins https://charts.jenkins.io || true
        helm repo update

    - name: Instalar Jenkins usando Helm
      shell: |
        helm upgrade --install {{ jenkins_release_name }} jenkins/jenkins \
          --namespace {{ helm_namespace }} \
          --create-namespace=false \
          --values /tmp/values.yaml \
          --version {{ jenkins_chart_version }}