# playbooks\master_copy_values.yml

- name: Copiar values.yaml a los masters
  hosts: masters
  gather_facts: false
  serial: 1
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Renderizar values.yaml.j2 en el controlador
      ansible.builtin.template:
        src: ../roles/jenkins/templates/values.yaml.j2
        dest: /tmp/values.yaml
      delegate_to: localhost

    - name: Copiar values.yaml al master usando scp automático
      ansible.builtin.shell: |
        scp -i /root/.ssh/cluster_k3s/shared/id_rsa_shared_cluster -o StrictHostKeyChecking=no /tmp/values.yaml core@{{ inventory_hostname }}:/home/core/values.yaml
      delegate_to: localhost